
const MASK_LOWERCASE_TEXT = 'a'
const MASK_UPPERCASE_TEXT = 'A'
const MASK_INCLUDE_ZERO_NUMBER = '0'
const MASK_EXCLUDE_ZERO_NUMBER = '9'
const MASK_INCLUDE_EMPTY_NUMBER = '#'

const STRING_MASK_LIST = [ MASK_LOWERCASE_TEXT, MASK_UPPERCASE_TEXT ]
const NUMBER_MASK_LIST = [
  MASK_INCLUDE_ZERO_NUMBER,
  MASK_EXCLUDE_ZERO_NUMBER,
  MASK_INCLUDE_EMPTY_NUMBER,
]
const MASK_LIST = [
  ...STRING_MASK_LIST,
  ...NUMBER_MASK_LIST,
]

export {
  STRING_MASK_LIST,
  NUMBER_MASK_LIST,
  MASK_LIST,
}

